config/routes.rb
Rails.application.routes.draw do

  get 'carts' => 'public/carts#index', as: 'carts'
  post 'carts' => 'public/carts#create'
  delete 'carts/destroy_all' => 'public/carts#destroy_all'
  patch 'carts/:id' => 'public/carts#update', as: 'cart'
  delete 'carts/:id' => 'public/carts#destroy'

  get 'order' => 'public/order#new', as: 'order'
  post 'confirm' => 'public/order#confirm', as: 'confirm'
  get 'thanks' => 'public/order#thanks', as: 'thanks'
  get 'orders' => 'public/order#index', as: 'orders'
  get 'order/:id' => 'public/order#show', as: 'order_show'
  put 'order/create' => 'public/order#create', as: 'order_create'

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get '/about', to: 'public/homes#about', as: 'about'
  get '/comfirm', to: 'public/homes#comfirm', as: 'comfirm'

  get '/mypage', to: 'public/customers#show', as: 'customer'
  get '/mypage/edit', to: 'public/customers#edit', as: 'edit_customer'
  patch '/mypage/update' => 'public/customers#update', as: 'update_customer'

  get '/bento/index', to: 'public/bento_box#index', as: 'bento_index'
  get '/bento/:id', to: 'public/bento_box#show', as: 'bento'

  get '/dishes', to: 'public/dishes#index', as: 'dishes'
  get '/dish/:id', to: 'public/dishes#show', as: 'dish'
  get '/genre/search/:id' => 'public/searches#genre_search', as: 'genre_search'
  get '/genre/dish/search/:id' => 'public/searches#genre_dish_search', as: 'genre_dish_search'
  get '/genre/recommend' => 'public/searches#recommend_search', as: 'recommend_search'
  get '/genre/new' => 'public/searches#new_search', as: 'new_search'
  get '/genre/dish/new' => 'public/searches#new_dish_search', as: 'new_dish_search'
  post '/address' => 'public/address#create', as: 'address'
  get '/address/:id' => 'public/address#edit', as: 'edit_address'
  patch '/address/update/:id' => 'public/address#update', as: 'update_address'
  delete '/address/:id' => 'public/address#destroy', as: 'destroy_address'



  namespace :admin do
    root to: "homes#top"
    resources :bento, :customer ,:dishes ,:genres ,:genre_dishes
    put '/recommend/:id', to: 'bento#recommend', as: 'recommend'
    get '/orders', to: 'orders#index', as: 'orders'
    get '/order/:id', to: 'orders#show', as: 'order'
    put '/order/:id', to: 'orders#update', as: 'order_update'
    put '/order/:id/orderdetail/:detail_id', to: 'order_details#update', as: 'order_detail_update'
    get '/genre/search/:id' => 'searches#genre_search', as: 'genre_search'
    get '/genre/dish/search/:id' => 'searches#genre_dish_search', as: 'genre_dish_search'
    get '/genre/dish/new' => 'searches#new_dish_search', as: 'new_dish_search'
    get '/genre/recommend' => 'searches#recommend_search', as: 'recommend_search'
    get '/genre/new' => 'searches#new_search', as: 'new_search'
    get '/customer/:id/orders' => 'customer#orders', as: 'customer_orders'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_one :order_making_time
  attribute :status, :integer, default: 0

  enum status: {
    waiting_production: 0,
    in_production: 1,
    waiting_delivery: 2,
    delivering: 3,
    delivered: 4
   }

   validates :name, presence: true
   validates :address, presence: true
   validates :post_code, presence: true
   validates :total_payment, presence: true
   validates :delivery_time, presence: true


  def address_display
  '〒' + post_code.to_s + ' ' + address + ' ' + name
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
#注文履歴管理

  def index
    @orders = Order.all.page(params[:page]).order(id: "DESC")

  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.status == "waiting_delivery"
      #ステータスを配送中に変える
      @order.status = "delivering"
      @order.order_making_time.shipping_start_at = Time.zone.now
      @order.order_making_time.save
      @order.save
      redirect_to admin_order_path(@order), notice: "変更を完了しました"
    elsif @order.status == "delivering"
      #ステータスを配送済みに変更する
      @order.status = "delivered"
      @order.order_making_time.shipping_end_at = Time.zone.now
      @order.order_making_time.save
      @order.save
      redirect_to admin_order_path(@order), notice: "変更を完了しました"
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def order_making_time_params
    params.require(:order_making_time).permit(:orer_id, :start_at, :end_at, :shipping_start_at, :shipping_end_at)
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-12">
      <div class="title-body">
        <h2>注文履歴一覧</h2>
      </div>
      <div>
        <%= flash[:notice] %>
      </div>

      <table class="table table-striped table-hover mt-3 mobile-blocky" style="background-color: #fff;">
        <thead>
          <tr>
            <th>注文日時</th>
            <th>注文者</th>
            <th>お届け先</th>
            <th>注文商品</th>
            <th>総額</th>
            <th>希望配送時間</th>
            <th>配送状況</th>
            <th>総製作時間</th>
            <th>配達時間</th>
          </tr>
        </thead>

        <% @orders.each do |order| %>
          <tr class="institution_index_tbody_tr" data-href="order/<%= order.id %>">
            <td>
              <%= link_to "#{order.created_at.strftime('%Y/%m/%d')}", order_show_path(order) ,class:"link-color" %>
            </td>
            <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
            <td><%= order.address_display %></td>
            <td>
              <% order.order_details.each do |order_detail| %>
                <%= order_detail.bento_box.name %>　<%= order_detail.amount %>個<br>
              <% end %>
            </td>
            <td>
              <%= order.total_payment %>円
            </td>
            <td>
              <% if order.delivery_time %>
                <%= order.delivery_time.strftime('%Y/%m/%d %H時%M分') %>
              <% end %>
            </td>
            <td>
              <%= order.status_i18n %>
            </td>

            <% if order.order_making_time %>

              <% if order.order_making_time.end_at %>
                <td>
                  <%= order.order_making_time.elapsed_time %>
                </td>
              <% elsif order.order_making_time.start_at %>
                <td class="bg-warning">
                </td>
              <% else %>
                <td class="bg-danger">
                </td>
              <% end %>
              <% if order.order_making_time.shipping_end_at %>
                <td>
                  <%= order.order_making_time.shipping_elapsed_time %>
                </td>
              <% elsif order.order_making_time.shipping_start_at %>
                <td class="bg-warning">
                </td>
              <% else %>
                <td class="bg-danger">
                </td>
              <% end %>
            <% else %>
                <td class="bg-danger">
                </td>
                <td class="bg-danger">
                </td>
            <% end %>

          </tr>
        <% end %>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-12">
      <div class="title-body">
        <h2>注文履歴詳細</h2>
      </div>
      <% if flash[:notice] %>
        <%= notice %>
      <% end %>
      <div class="row d-flex justify-content-center m-3">
        <div class="col-md-8 max-box d-flex flex-wrap justify-content-center">
          <% @nedan = 0 %>
          <% @order.order_details.each do |f| %>
            <% @nedan = @nedan + f.subtotal %>
            <div class="card m-3" style="width: 13rem;">
                <%= image_tag f.bento_box.bento_image,class: "m-auto card-img-top"%>
              <div class="card-body d-flex flex-column justify-content-center">
                <h6 class="p-2 gray"><%= f.bento_box.name %></h6>
                <p class="card-text m-1"><%= f.bento_box.price%>円</p>
                <p class="card-text m-1"><%= f.amount %>個</p>
                <p class="card-text m-1 gray">小計：　<%= f.subtotal%>円</p>
                <% if f.making_status == "completed" %>
                <p class="card-text m-1 text-success"><%= f.making_status_i18n %></p>
                <% else %>
                <p class="card-text m-1 text-white bg-danger"><%= f.making_status_i18n %></p>
                <% end %>
                <% time = f.order_detail_making_time %>
                <% if time %>
                  <% if time.start_at %>
                    <p class="card-text m-1 gray">製作開始</p>
                    <p class="card-text m-1"><%= time.start_at.strftime('%Y/%m/%d %H時%M分') %></p>
                  <% end %>
                  <% if time.end_at %>
                    <p class="card-text m-1 gray">製作終了</p>
                    <p class="card-text m-1"><%= time.end_at.strftime('%Y/%m/%d %H時%M分') %></p>
                    <p class="card-text m-1 gray">製作時間</p>
                    <p class="card-text m-1"><%= time.elapsed_time %></p>
                  <% end %>
                <% end %>
                <% if f.making_status == "waiting" %>
                  <%= link_to "製作開始",admin_order_detail_update_path(@order, f), method: :put, class: "btn btn-outline-primary btn-sm stretched-link", "data-confirm" => "製作を開始しますか？" %>
                <% elsif f.making_status == "in_progress" %>
                  <%= link_to "製作終了",admin_order_detail_update_path(@order, f), method: :put, class: "btn btn-outline-primary btn-sm stretched-link", "data-confirm" => "完成しましたか？" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-md-4">
          <div class="mb-0 p-2" style="background-color: #ffffff; border-radius: 10px;">
            <h6 class="mb-0 p-2 text-left gray">合計金額</h6>
            <h6 class="mt-0 p-2"><%= @nedan %>円</h6>
            <h6 class="mb-0 p-2 text-left gray">お届け先</h6>
            <h6 class="mt-0 p-2"><%= @order.address_display %></h6>
            <h6 class="mb-0 p-2 text-left gray">希望お届け時間</h6>
            <h6 class="mt-0 p-2"><%= @order.delivery_time.strftime('%Y/%m/%d %H時%M分') %></h6>
            <h6 class="mb-0 p-2 text-left gray">配送状況</h6>
            <% if @order.status == "waiting_production" || @order.status == "in_production" %>
              <h6 class="mt-1 p-2 text-white bg-warning"><%= @order.status_i18n %></h6>
            <% elsif @order.status == "waiting_delivery" %>
              <h6 class="mt-1 p-2 text-white bg-danger"><%= @order.status_i18n %></h6>
              <%= link_to "配送開始",admin_order_update_path(@order), method: :put, class: "m-1 btn btn-outline-primary stretched-link", "data-confirm" => "配送準備はできていますか？" %>
            <% elsif @order.status == "delivering" %>
              <h6 class="mt-1 p-2 text-white bg-danger"><%= @order.status_i18n %></h6>
              <%= link_to "配送完了",admin_order_update_path(@order), method: :put, class: "m-1 btn btn-outline-primary stretched-link", "data-confirm" => "配送お疲れ様です" %>
            <% else %>
              <h6 class="mt-1 p-2 text-success"><%= @order.status_i18n %></h6>
            <% end %>
            <% if @order.order_making_time %>
              <% if @order.order_making_time.start_at %>
                <h6 class="mb-0 p-2 text-left gray">製作開始</h6>
                <h6 class="mt-0 p-2"><%= @order.order_making_time.start_at.strftime('%Y/%m/%d %H時%M分') %></h6>
              <% end %>
              <% if @order.order_making_time.end_at %>
                <h6 class="mb-0 p-2 text-left gray">製作終了</h6>
                <h6 class="mt-0 p-2"><%= @order.order_making_time.end_at.strftime('%Y/%m/%d %H時%M分') %></h6>
                <h6 class="mb-0 p-2 text-left gray">総製作時間</h6>
                <h6 class="mt-0 p-2"><%= @order.order_making_time.elapsed_time %></h6>
              <% end %>
              <% if @order.order_making_time.shipping_start_at %>
                <h6 class="mb-0 p-2 text-left gray">配送開始</h6>
                <h6 class="mt-0 p-2"><%= @order.order_making_time.shipping_start_at.strftime('%Y/%m/%d %H時%M分') %></h6>
              <% end %>
              <% if @order.order_making_time.shipping_end_at %>
                <h6 class="mb-0 p-2 text-left gray">配送完了時間</h6>
                <h6 class="mt-0 p-2"><%= @order.order_making_time.shipping_end_at.strftime('%Y/%m/%d %H時%M分') %></h6>
                <h6 class="mb-0 p-2 text-left gray">配送時間</h6>
                <h6 class="mt-0 p-2"><%= @order.order_making_time.shipping_elapsed_time %></h6>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "一覧に戻る", admin_orders_path , class: "link-color" %>
    </div>
  </div>
</div>