config/routes.rb
Rails.application.routes.draw do

  get 'carts' => 'public/carts#index', as: 'carts'
  post 'carts' => 'public/carts#create'
  delete 'carts/destroy_all' => 'public/carts#destroy_all'
  patch 'carts/:id' => 'public/carts#update', as: 'cart'
  delete 'carts/:id' => 'public/carts#destroy'

  get 'order' => 'public/order#new', as: 'order'
  post 'confirm' => 'public/order#confirm', as: 'confirm'
  get 'thanks' => 'public/order#thanks', as: 'thanks'
  get 'orders' => 'public/order#index', as: 'orders'
  get 'order/:id' => 'public/order#show', as: 'order_show'
  put 'order/create' => 'public/order#create', as: 'order_create'

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get '/about', to: 'public/homes#about', as: 'about'
  get '/comfirm', to: 'public/homes#comfirm', as: 'comfirm'

  get '/mypage', to: 'public/customers#show', as: 'customer'
  get '/mypage/edit', to: 'public/customers#edit', as: 'edit_customer'
  patch '/mypage/update' => 'public/customers#update', as: 'update_customer'

  get '/bento/index', to: 'public/bento_box#index', as: 'bento_index'
  get '/bento/:id', to: 'public/bento_box#show', as: 'bento'

  get '/dishes', to: 'public/dishes#index', as: 'dishes'
  get '/dish/:id', to: 'public/dishes#show', as: 'dish'
  get '/genre/search/:id' => 'public/searches#genre_search', as: 'genre_search'
  get '/genre/dish/search/:id' => 'public/searches#genre_dish_search', as: 'genre_dish_search'
  get '/genre/recommend' => 'public/searches#recommend_search', as: 'recommend_search'
  get '/genre/new' => 'public/searches#new_search', as: 'new_search'
  get '/genre/dish/new' => 'public/searches#new_dish_search', as: 'new_dish_search'
  post '/address' => 'public/address#create', as: 'address'
  get '/address/:id' => 'public/address#edit', as: 'edit_address'
  patch '/address/update/:id' => 'public/address#update', as: 'update_address'
  delete '/address/:id' => 'public/address#destroy', as: 'destroy_address'



  namespace :admin do
    root to: "homes#top"
    resources :bento, :customer ,:dishes ,:genres ,:genre_dishes
    put '/recommend/:id', to: 'bento#recommend', as: 'recommend'
    get '/orders', to: 'orders#index', as: 'orders'
    get '/order/:id', to: 'orders#show', as: 'order'
    put '/order/:id', to: 'orders#update', as: 'order_update'
    put '/order/:id/orderdetail/:detail_id', to: 'order_details#update', as: 'order_detail_update'
    get '/genre/search/:id' => 'searches#genre_search', as: 'genre_search'
    get '/genre/dish/search/:id' => 'searches#genre_dish_search', as: 'genre_dish_search'
    get '/genre/dish/new' => 'searches#new_dish_search', as: 'new_dish_search'
    get '/genre/recommend' => 'searches#recommend_search', as: 'recommend_search'
    get '/genre/new' => 'searches#new_search', as: 'new_search'
    get '/customer/:id/orders' => 'customer#orders', as: 'customer_orders'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
#カテゴリー検索機能
  def genre_search
    @genre_id = params[:id]
    @bentoes = BentoBox.where(genre_id: @genre_id).page(params[:page]).per(6)
    @genre = Genre.find(params[:id])
    @genres = Genre.all
  end

  def genre_dish_search
    @genre_dish_id = params[:id]
    @dishes = Dish.where(genre_id: @genre_dish_id).page(params[:page]).per(6)
    @genre = GenreDish.find(params[:id])
    @genres = GenreDish.all
  end

  def recommend_search
    @bento = BentoBox.find_by(recommended: true)
    @genres = Genre.all
  end

  def new_search
    @bentoes = BentoBox.order(id: :DESC).page(params[:page]).per(6)
    @genres = Genre.all
  end

  def new_dish_search
    @dishes = Dish.order(id: :DESC).page(params[:page]).per(6)
    @genres = GenreDish.all
  end


end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/searches/_genre.html.erb
<div class="genre_search">
  <table class="table table-hover">
    <tr>
      <th style="border-bottom: 6px solid #e63d00;" >カテゴリー検索</th>
    </tr>
    <tr class="institution_index_tbody_tr" data-href="/admin/bento">
      <td><%= link_to "一覧",admin_bento_index_path, class: "link-color" %></td>
    </tr>
    <tr class="institution_index_tbody_tr" data-href="/admin/genre/new">
      <td><%= link_to "一覧(新しい順)",admin_new_search_path, class: "link-color" %></td>
    </tr>
    <% @recommended_bento = BentoBox.find_by(recommended: true) %>
    <% if @recommended_bento %>
      <tr class="institution_index_tbody_tr" data-href="/admin/genre/recommend">
        <td><%= link_to "おすすめ",admin_recommend_search_path , class: "link-color" %></td>
      </tr>
    <% end %>

    <% @genres.each do |genre| %>
      <tr class="institution_index_tbody_tr" data-href="/admin/genre/search/<%= genre.id %>">
        <td><%= link_to genre.name, admin_genre_search_path(genre.id) , class: "link-color" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/searches/_genre_dish.html.erb
<div class="genre_search">
  <table class="table table-hover ">
    <tr>
      <th style="border-bottom: 6px solid #e63d00;">カテゴリー検索</th>
    </tr>
    <tr class="institution_index_tbody_tr" data-href="/admin/dishes">
      <td><%= link_to "一覧",admin_dishes_path , class: "link-color" %></td>
    </tr>
    <tr class="institution_index_tbody_tr" data-href="/admin/genre/dish/new">
      <td><%= link_to "一覧(新しい順)",admin_new_dish_search_path , class: "link-color" %></td>
    </tr>

    <% @genres.each do |genre| %>
      <tr class="institution_index_tbody_tr" data-href="/admin/genre/dish/search/<%= genre.id %>">
        <td><%= link_to genre.name, admin_genre_dish_search_path(genre.id) , class: "link-color" %></td>
      </tr>
    <% end %>



  </table>
</div>

app/views/admin/searches/genre_dish_search.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-md-2">
      <% if @genres.present? %>
        <%= render 'admin/searches/genre_dish.html.erb' %>
      <% end %>
    </div>
    <div class="col-md-10">
      <div class="title-body">
        <h2>おかず一覧(<%= @genre.name %>)</h2>
      </div>

      <div class="max-box d-flex flex-wrap justify-content-center">
        <% if @dishes.present? %>
          <% @dishes.each do |dish| %>
            <div class="card m-3" style="width: 18rem;">
              <%= image_tag dish.dish_image, class: "card-img-top", alt: dish.name %>
              <div class="card-body d-flex flex-column">
                <h5 class="card-title dark m-0"><%= dish.name %></h5>
                <p class="card-text m-0"><%= dish.introduction %></p>
                <div class="float-right mt-auto">
                  <%= link_to "詳細を見る",admin_dish_path(dish), class: "btn btn-outline-primary btn-sm stretched-link"%>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>データが存在しません</p>
        <% end %>
      </div>
      <%= paginate @dishes %>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "おかずを追加する",new_admin_dish_path %>
    </div>
  </div>
</div>

app/views/admin/searches/genre_search.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-md-2">
      <% if @genres.present? %>
        <%= render 'admin/searches/genre.html.erb' %>
      <% end %>
    </div>
    <div class="col-md-10">
      <div class="title-body">
        <h2>弁当一覧(<%= @genre.name %>)</h2>
      </div>

      <div class="max-box d-flex flex-wrap justify-content-center">
        <% if @bentoes.present? %>
          <% @bentoes.each do |bento| %>
            <div class="card m-3" style="width: 18rem;">
              <%= image_tag bento.bento_image, class: "card-img-top", alt: bento.name %>
              <div class="card-body d-flex flex-column">
                <h5 class="card-title m-0 dark "><%= bento.name %></h5>
                <% if bento.recommended %>
                  <h6 class="recommended">おすすめ中</h6>
                <% end %>
                <p class="card-text m-0"><%= bento.introduction %></p>
                <div class="float-right mt-auto">
                  <%= link_to "詳細を見る",admin_bento_path(bento), class: "btn btn-outline-dark btn-sm stretched-link" %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>データが存在しません</p>
        <% end %>
      </div>
      <%= paginate @bentoes %>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "弁当を追加する",new_admin_bento_path, class: "link-color" %>
    </div>
  </div>
</div>

app/views/admin/searches/new_dish_search.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-md-2">
      <% if @genres.present? %>
        <%= render 'admin/searches/genre_dish.html.erb' %>
      <% end %>
    </div>
    <div class="col-md-10">
      <div class="title-body">
        <h2>おかず一覧(新しい順)</h2>
      </div>

      <div class="max-box d-flex flex-wrap justify-content-center">
        <% if @dishes.present? %>
          <% @dishes.each do |dish| %>
            <div class="card m-3" style="width: 18rem;">
              <%= image_tag dish.dish_image, class: "card-img-top", alt: dish.name %>
              <div class="card-body d-flex flex-column">
                <h5 class="card-title dark m-0"><%= dish.name %></h5>
                <p class="card-text m-0"><%= dish.introduction %></p>
                <div class="float-right mt-auto">
                  <%= link_to "詳細を見る",admin_dish_path(dish), class: "btn btn-outline-dark btn-sm stretched-link"%>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>データが存在しません</p>
        <% end %>
      </div>
      <%= paginate @dishes %>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "おかずを追加する",new_admin_dish_path %>
    </div>
  </div>
</div>

app/views/admin/searches/new_search.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-md-2">
      <% if @genres.present? %>
        <%= render 'admin/searches/genre.html.erb' %>
      <% end %>
    </div>
    <div class="col-md-10">
      <div class="title-body">
        <h2>弁当一覧(新しい順)</h2>
      </div>

      <div class="max-box d-flex flex-wrap justify-content-center">
        <% if @bentoes.present? %>
          <% @bentoes.each do |bento| %>
            <div class="card m-3" style="width: 18rem;">
              <%= image_tag bento.bento_image, class: "card-img-top", alt: bento.name %>
              <div class="card-body d-flex flex-column">
                <h5 class="card-title m-0 dark "><%= bento.name %></h5>
                <% if bento.recommended %>
                  <h6 class="recommended">おすすめ中</h6>
                <% end %>
                <p class="card-text m-0"><%= bento.introduction %></p>
                <div class="float-right mt-auto">
                  <%= link_to "詳細を見る",admin_bento_path(bento), class: "btn btn-outline-dark btn-sm stretched-link" %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>データが存在しません</p>
        <% end %>
      </div>
      <%= paginate @bentoes %>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "弁当を追加する",new_admin_bento_path, class: "link-color" %>
    </div>
  </div>
</div>

app/views/admin/searches/recommend_search.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-md-2">
      <% if @genres.present? %>
        <%= render 'admin/searches/genre.html.erb' %>
      <% end %>
    </div>
    <div class="col-md-10">
      <div class="title-body">
        <h2>弁当一覧(おすすめ)</h2>
      </div>

      <div class="max-box d-flex flex-wrap justify-content-center">
        <% if @bento.present? %>
            <div class="card m-3" style="width: 18rem;">
              <%= image_tag @bento.bento_image, class: "card-img-top", alt: @bento.name %>
              <div class="card-body d-flex flex-column">
                <h5 class="card-title m-0 dark"><%= @bento.name %></h5>
                <h6 class="recommended">おすすめ中</h6>
                <p class="card-text m-0"><%= @bento.introduction %></p>
                <div class="float-right mt-auto">
                  <%= link_to "詳細を見る",admin_bento_path(@bento), class: "btn btn-outline-dark btn-sm stretched-link" %>
                </div>
              </div>
            </div>
        <% else %>
          <p>データが存在しません</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "弁当を追加する",new_admin_bento_path, class: "link-color" %>
    </div>
  </div>
</div>