config/routes.rb
Rails.application.routes.draw do

  get 'carts' => 'public/carts#index', as: 'carts'
  post 'carts' => 'public/carts#create'
  delete 'carts/destroy_all' => 'public/carts#destroy_all'
  patch 'carts/:id' => 'public/carts#update', as: 'cart'
  delete 'carts/:id' => 'public/carts#destroy'

  get 'order' => 'public/order#new', as: 'order'
  post 'confirm' => 'public/order#confirm', as: 'confirm'
  get 'thanks' => 'public/order#thanks', as: 'thanks'
  get 'orders' => 'public/order#index', as: 'orders'
  get 'order/:id' => 'public/order#show', as: 'order_show'
  put 'order/create' => 'public/order#create', as: 'order_create'

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get '/about', to: 'public/homes#about', as: 'about'
  get '/comfirm', to: 'public/homes#comfirm', as: 'comfirm'

  get '/mypage', to: 'public/customers#show', as: 'customer'
  get '/mypage/edit', to: 'public/customers#edit', as: 'edit_customer'
  patch '/mypage/update' => 'public/customers#update', as: 'update_customer'

  get '/bento/index', to: 'public/bento_box#index', as: 'bento_index'
  get '/bento/:id', to: 'public/bento_box#show', as: 'bento'

  get '/dishes', to: 'public/dishes#index', as: 'dishes'
  get '/dish/:id', to: 'public/dishes#show', as: 'dish'
  get '/genre/search/:id' => 'public/searches#genre_search', as: 'genre_search'
  get '/genre/dish/search/:id' => 'public/searches#genre_dish_search', as: 'genre_dish_search'
  get '/genre/recommend' => 'public/searches#recommend_search', as: 'recommend_search'
  get '/genre/new' => 'public/searches#new_search', as: 'new_search'
  get '/genre/dish/new' => 'public/searches#new_dish_search', as: 'new_dish_search'
  post '/address' => 'public/address#create', as: 'address'
  get '/address/:id' => 'public/address#edit', as: 'edit_address'
  patch '/address/update/:id' => 'public/address#update', as: 'update_address'
  delete '/address/:id' => 'public/address#destroy', as: 'destroy_address'



  namespace :admin do
    root to: "homes#top"
    resources :bento, :customer ,:dishes ,:genres ,:genre_dishes
    put '/recommend/:id', to: 'bento#recommend', as: 'recommend'
    get '/orders', to: 'orders#index', as: 'orders'
    get '/order/:id', to: 'orders#show', as: 'order'
    put '/order/:id', to: 'orders#update', as: 'order_update'
    put '/order/:id/orderdetail/:detail_id', to: 'order_details#update', as: 'order_detail_update'
    get '/genre/search/:id' => 'searches#genre_search', as: 'genre_search'
    get '/genre/dish/search/:id' => 'searches#genre_dish_search', as: 'genre_dish_search'
    get '/genre/dish/new' => 'searches#new_dish_search', as: 'new_dish_search'
    get '/genre/recommend' => 'searches#recommend_search', as: 'recommend_search'
    get '/genre/new' => 'searches#new_search', as: 'new_search'
    get '/customer/:id/orders' => 'customer#orders', as: 'customer_orders'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bento_box.rb
class BentoBox < ApplicationRecord
  has_many :bento_box_dishes
  has_many :dishes ,through: :bento_box_dishes
  has_many :carts
  has_many :order_details
  has_many :stars, foreign_key: 'star_id'
  belongs_to :genre, foreign_key: 'genre_id'
  has_one_attached :bento_image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  before_create :default_image

  def default_image
    if !self.bento_image.attached?
      self.bento_image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'noimage.jpg')), filename: 'noimage.jpg', content_type: 'image/jpg')
    end
  end
end

app/controllers/admin/bento_controller.rb
class Admin::BentoController < ApplicationController
  #追加したい機能　弁当ごとの注文されてきた数の記録　売れ筋商品の見極め 
  before_action :authenticate_admin!

  def index
    # お弁当の一覧
    @bentoes = BentoBox.page(params[:page]).per(6)
    @genres = Genre.all
  end

  def show
    # お弁当詳細
    @bento = BentoBox.find(params[:id])
  end

  def edit
    # お弁当編集
    @bento = BentoBox.find(params[:id])
    @dishes = Dish.all
    @genres = Genre.all
  end

  def update
    # 編集したお弁当更新
    @bento = BentoBox.find(params[:id])
    @dishes = Dish.all
    @genres = Genre.all
    if @bento.update(bento_params)
      redirect_to admin_bento_path(@bento), notice: "変更内容を保存しました"
    else
      render :edit
    end
  end

  def new
    # 新しく作る
    @bento = BentoBox.new
    @dishes = Dish.all
    @genres = Genre.all
  end

  def create
    @bento = BentoBox.new(bento_params)
    @dishes = Dish.all
    @genres = Genre.all
    if @bento.save
      redirect_to admin_bento_path(@bento), notice: "作成を完了しました"
    else
      render :new
    end
  end

  def destroy
    @bento = BentoBox.find(params[:id])
    @bento.destroy
    redirect_to admin_bento_index_path
  end

  def recommend
    BentoBox.update_all(recommended: false)
    bento = BentoBox.find(params[:id])
    bento.update(recommended: true)
    redirect_to admin_bento_path(bento)
  end

  private

  def bento_params
    params.require(:bento_box).permit(:name, :introduction, :image,:price,:genre_id,:is_active,:bento_image,dish_ids:[])
  end

  def dish_params
    params.require(:dish).permit(:name, :introduction, :image, :genre_id,:is_active,:dish_image)
  end
end

app/helpers/admin/bento_helper.rb
module Admin::BentoHelper
end

app/views/admin/bento/edit.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-12">
      <div class="title-body">
        <h2>弁当編集</h2>
      </div>
      <% if @genres.present? %>
        <%= form_with model:@bento, url: admin_bento_path(@bento), local:true do |f| %>
        <% if @bento.errors.any? %>
          <%= @bento.errors.count %>件のエラーが発生しました
          <ul>
            <% @bento.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
          <div class="row m-3 gray" >
            <div class="col-md-6 m-auto p-3 max-width " >
              <div class="field text-left">
                <%= f.label :name,"名前" %><br />
                <%= f.text_field :name , autofocus: true, :placeholder => "名前" ,size: 30 , class: "max-width" %>
              </div>
              <div class="field text-left">
                <%= f.label :introduction,"紹介文" %><br />
                <%= f.text_area :introduction ,:placeholder => "紹介文" ,size: "35x5" , class: "max-width" %>
              </div>
              <div class="field text-left">
                <%= f.label :price,"価格（税抜）" %><br />
                <%= f.text_field :price ,:placeholder => "価格" ,size: "35x5" , class: "max-width" %>
              </div>
              <div class="field text-left">
                <%= f.label :genre_id,"カテゴリー" %><br />
                <%= f.collection_select(:genre_id, @genres, :id, :name) %>
              </div>
              <div class="field text-left">
                <%= f.label :image,"画像" %><br />
                <%= f.file_field :bento_image, accept: "image/*" , class: "max-width" %>
              </div>
              <div class="field text-left">
                <%= f.label :is_active,"販売状況" %><br />
                <%= f.radio_button :is_active, :true %>
                  販売中
                <%= f.radio_button :is_active, :false %>
                  販売停止中
              </div>
            </div>
            <div class="col-md-6 m-auto p-3 field text-left max-width">
              <%= f.label :genre_id,"おかず" %><br />
              <%= f.collection_check_boxes(:dish_ids, @dishes, :id, :name) do |b| %>
                <label class="checkbox-inline">
                <%= b.check_box class:"form-control2" do %>
                    <%= b.check_box + b.text %>
                <% end %>
                  <%= b.label {b.text} %>
                  <%= image_tag b.object.dish_image,size: "50x30"%>
                </label>
              <% end %>
            </div>
            </div>
            <div class="row">
              <div class="col-md-8 offset-4"><br />
                <%= f.submit "変更を保存する" ,class: "btn btn-outline-success"%>
              </div>
          </div>
        <% end %>
      <% else %>
        <p><%= link_to "おかずカテゴリーを作成してください",admin_genres_path, class: "m-5 btn btn-sm btn-primary" %></p>
      <% end %>
      </div>
    </div>
  <div class="row float-right">
    <div>
      <%= link_to "詳細に戻る",admin_bento_path(@bento), class: "link-color" %>
    </div>
  </div>
</div>

app/views/admin/bento/index.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-md-2">
      <% if @genres.present? %>
        <%= render 'admin/searches/genre.html.erb' %>
      <% end %>
    </div>
    <div class="col-md-10">
      <div class="title-body">
        <h2>弁当一覧</h2>
      </div>
      <div>
        <%= flash[:notice] %>
      </div>
      <div class="max-box d-flex flex-wrap justify-content-center">
        <% if @bentoes.present? %>
          <% @bentoes.each do |bento| %>
            <div class="card m-3" style="width: 18rem;">
              <%= image_tag bento.bento_image, class: "card-img-top", alt: bento.name %>
              <div class="card-body d-flex flex-column">
                <h5 class="card-title m-0 dark "><%= bento.name %></h5>
                <% if bento.recommended %>
                  <h6 class="recommended">おすすめ中</h6>
                <% end %>
                <p class="card-text m-0"><%= bento.introduction %></p>
                <div class="float-right mt-auto">
                  <%= link_to "詳細を見る",admin_bento_path(bento), class: "btn btn-outline-dark btn-sm stretched-link" %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>データが存在しません</p>
        <% end %>
      </div>
      <%= paginate @bentoes %>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "弁当を追加する",new_admin_bento_path, class: "link-color" %>
    </div>
  </div>
</div>

app/views/admin/bento/new.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-12">
      <div class="title-body">
        <h2>弁当新規作成</h2>
      </div>
      <% if @genres.present? %>
        <%= form_with model:@bento, url: admin_bento_index_path, local:true do |f| %>
        <% if @bento.errors.any? %>
          <%= @bento.errors.count %>件のエラーが発生しました
          <ul>
            <% @bento.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
          <div class="row m-3 gray">
            <div class="col-md-6 m-auto p-3 max-width">
              <div class="field text-left">
                <%= f.label :name,"名前" %><br />
                <%= f.text_field :name , autofocus: true, :placeholder => "名前" ,size: 30 , class: "max-width" %>
              </div>
              <div class="field text-left">
                <%= f.label :introduction,"紹介文" %><br />
                <%= f.text_area :introduction ,:placeholder => "紹介文" ,size: "35x5" , class: "max-width" %>
              </div>
              <div class="field text-left">
                <%= f.label :price,"価格（税抜）" %><br />
                <%= f.text_field :price ,:placeholder => "価格" ,size: "35x5" , class: "max-width" %>
              </div>
              <div class="field text-left">
                <%= f.label :genre_id,"カテゴリー" %><br />
                <%= f.collection_select(:genre_id, @genres, :id, :name) %>
              </div>
              <div class="field text-left">
                <%= f.label :image,"画像" %><br />
                <%= f.file_field :bento_image, accept: "image/*" , class: "max-width" %>
              </div>
            </div>
            <div class="col-md-6 m-auto p-3 field text-left">
              <%= f.label :dish_id,"おかず" %><br />
              <%= f.collection_check_boxes(:dish_ids, @dishes, :id, :name) do |b| %>
                <label class="checkbox-inline">
                <%= b.check_box class:"form-control2" do %>
                    <%= b.check_box + b.text %>
                <% end %>
                  <%= image_tag b.object.dish_image,size: "50x50"%>
                  <%= b.label {b.text} %>
                </label>
              <% end %>
            </div>
            </div>
          <div class="row">
            <div class="col-md-8 offset-4"><br />
              <%= f.submit "作成する" ,class: "btn btn-outline-success"%>
            </div>
          </div>
        <% end %>
      <% else %>
        <p><%= link_to "おかずカテゴリーを作成してください",admin_genres_path, class: "m-5 btn btn-sm btn-primary" %></p>
      <% end %>
      </div>
    </div>
  <div class="row float-right">
    <div>
      <%= link_to "おかずを作成する",new_admin_dish_path , class: "link-color" %>
      <%= link_to "弁当一覧に戻る",admin_bento_index_path , class: "link-color" %>
    </div>
  </div>
</div>

app/views/admin/bento/show.html.erb
<div class="container-xxl p-5">
  <div class="row text-center">
    <div class="col-12">
      <div class="title-body">
        <h2><%= @bento.name %></h2>
      </div>
      <div>
        <%= flash[:notice] %>
      </div>
      <div class="row d-flex justify-content-center m-3 white p-2">
        <% if @bento.present? %>
          <div class="col-md-8 text-left ">
            <div class="row">
              <div class="col-md-6">
                <%= image_tag @bento.bento_image,class:"img-fluid" ,style: "width:50%;" %>
              </div>
              <div class="col-md-6">
                <h6 class="gray p-2 mt-1">紹介文</h6>
                　<%= @bento.introduction %>
                <h6 class="gray p-2">価格</h6>
                　<%= @bento.price %>円
                <h6 class="gray p-2">カテゴリー</h6>
                　<%= @bento.genre.name %>
                <h6 class="gray p-2">販売状況</h6>
                <% if @bento.is_active %>
                  <span class="text-success">　販売中</span>
                <% else %>
                  　販売停止中
                <% end %>
                <% if @bento.is_active %>
                  <h6 class="gray p-2">ステータス</h6>
                  <% if @bento.recommended %>
                    <h6 class="text-success">　おすすめ商品</h6>
                  <% else %>
                    <%= link_to "おすすめ商品にする",admin_recommend_path(@bento), method: :put , class: " m-2 btn btn-outline-dark btn-sm" %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <h4 class="gray p-2">おかず</h4>
            <div class = "row">
            <% @bento.dishes.each do |dish| %>
              <div class="mt-1">
                <%= link_to admin_dish_path(dish) , class: "col-md-3 link-color" do %>
                  <div class="text-center">
                    <%= image_tag dish.dish_image,size: "100x60" %>
                  </div>
                  <div class="text-center">
                    <%= dish.name %>
                  </div>
                <% end %>
              </div>
            <% end %>
            </div>
          </div>
        <% else %>
          <p>データが存在しません</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row float-right">
    <div>
      <%= link_to "編集する",edit_admin_bento_path(@bento),class: "mr-5 text-success" %>
      <%= link_to '削除する', admin_bento_path(@bento), method: :delete, data: { confirm: '本当に消しますか？' }, class: "text-danger mr-5"%>
      <%= link_to "弁当一覧に戻る",admin_bento_index_path ,class: "link-color" %>
    </div>
  </div>
</div>