config/routes.rb
Rails.application.routes.draw do

  get 'carts' => 'public/carts#index', as: 'carts'
  post 'carts' => 'public/carts#create'
  delete 'carts/destroy_all' => 'public/carts#destroy_all'
  patch 'carts/:id' => 'public/carts#update', as: 'cart'
  delete 'carts/:id' => 'public/carts#destroy'

  get 'order' => 'public/order#new', as: 'order'
  post 'confirm' => 'public/order#confirm', as: 'confirm'
  get 'thanks' => 'public/order#thanks', as: 'thanks'
  get 'orders' => 'public/order#index', as: 'orders'
  get 'order/:id' => 'public/order#show', as: 'order_show'
  put 'order/create' => 'public/order#create', as: 'order_create'

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get '/about', to: 'public/homes#about', as: 'about'
  get '/comfirm', to: 'public/homes#comfirm', as: 'comfirm'

  get '/mypage', to: 'public/customers#show', as: 'customer'
  get '/mypage/edit', to: 'public/customers#edit', as: 'edit_customer'
  patch '/mypage/update' => 'public/customers#update', as: 'update_customer'

  get '/bento/index', to: 'public/bento_box#index', as: 'bento_index'
  get '/bento/:id', to: 'public/bento_box#show', as: 'bento'

  get '/dishes', to: 'public/dishes#index', as: 'dishes'
  get '/dish/:id', to: 'public/dishes#show', as: 'dish'
  get '/genre/search/:id' => 'public/searches#genre_search', as: 'genre_search'
  get '/genre/dish/search/:id' => 'public/searches#genre_dish_search', as: 'genre_dish_search'
  get '/genre/recommend' => 'public/searches#recommend_search', as: 'recommend_search'
  get '/genre/new' => 'public/searches#new_search', as: 'new_search'
  get '/genre/dish/new' => 'public/searches#new_dish_search', as: 'new_dish_search'
  post '/address' => 'public/address#create', as: 'address'
  get '/address/:id' => 'public/address#edit', as: 'edit_address'
  patch '/address/update/:id' => 'public/address#update', as: 'update_address'
  delete '/address/:id' => 'public/address#destroy', as: 'destroy_address'



  namespace :admin do
    root to: "homes#top"
    resources :bento, :customer ,:dishes ,:genres ,:genre_dishes
    put '/recommend/:id', to: 'bento#recommend', as: 'recommend'
    get '/orders', to: 'orders#index', as: 'orders'
    get '/order/:id', to: 'orders#show', as: 'order'
    put '/order/:id', to: 'orders#update', as: 'order_update'
    put '/order/:id/orderdetail/:detail_id', to: 'order_details#update', as: 'order_detail_update'
    get '/genre/search/:id' => 'searches#genre_search', as: 'genre_search'
    get '/genre/dish/search/:id' => 'searches#genre_dish_search', as: 'genre_dish_search'
    get '/genre/dish/new' => 'searches#new_dish_search', as: 'new_dish_search'
    get '/genre/recommend' => 'searches#recommend_search', as: 'recommend_search'
    get '/genre/new' => 'searches#new_search', as: 'new_search'
    get '/customer/:id/orders' => 'customer#orders', as: 'customer_orders'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>弁当コック</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9235c0d6d5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="main">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000; border-bottom: 10px solid #e63d00">
        <% if admin_signed_in? %>
        <a class="navbar-brand" href="/admin"><h1>弁当コック</h1></a>
        <% else %>
        <a class="navbar-brand" href="/"><h1>弁当コック</h1></a>
        <% end %>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <% if admin_signed_in? %>
              <li class="nav-item text-right">
                <%= link_to "トップページ", admin_root_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "弁当一覧", admin_bento_index_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "会員一覧", admin_customer_index_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% elsif customer_signed_in? %>

              <li class="nav-item text-right">
                <%= link_to "マイページ", customer_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "商品一覧", bento_index_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "注文履歴一覧", orders_path, class: "nav-link" %>
              </li>
              <% if Cart.where(customer_id: current_customer.id).present? %>
                <li class="nav-item text-right">
                  <%= link_to "カート", carts_path, class: "nav-link" %>
                </li>
              <% end %>
              <li class="nav-item text-right">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "企業理念", about_path, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item text-right">
                <%= link_to "トップページ", root_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item text-right">
                <%= link_to "商品一覧", bento_index_path, class: "nav-link" %>
              </li>

              <li class="nav-item dropdown text-right">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  その他
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <div class="dropdown-item">
                    <%= link_to "企業理念", about_path, class: "link-color" %>
                  </div>
                  <div class="dropdown-item">
                    <%= link_to "従業員専用", comfirm_path, class: "link-color" %>
                  </div>

                </div>
              </li>
            <% end %>
          </ul>
        </div>

      </nav>
    </header>

    <body class="body-color">
      <%= yield %>
    </body>

    <footer>
    </footer>
  </div>


</html>